---
# OOB Management network default gateway
mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: default

name_servers:
  - 192.168.2.1
  - 8.8.8.8

# # Local users
# local_users:
#   # Define a new user, which is called "ansible"
#   - name: ansible
#     privilege: 15
#     role: network-admin
#     # Password set to "ansible". Same string as the device generates when configuring a username.
#     sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920

dns_domain: atd.lab
